### ISSUE TITLE
the session MANUAL bug

### ISSUE THREAD

**Issue by userjia** [BrickTrying/idea#1]
BUG: Write operations are not allowed in read-only mode (FlushMode.MANUAL): Turn your Session into FlushMode.COMMIT/AUTO or remove 'readOnly' marker from transaction definition.

:according to debug and compare with xiaochun forum, the session is not correctly assigned with AUTO filter

session can't be set to AUTO mode

web.xml loaded seems good

the reasonable way to call and set auto to session is like

export thread and get:

"818546553@qtp-1513757689-1@2865" prio=5 tid=0xf nid=NA runnable
  java.lang.Thread.State: RUNNABLE
	  at org.hibernate.internal.SessionImpl.setFlushMode(SessionImpl.java:1394)
	  at org.springframework.orm.hibernate4.support.OpenSessionInViewFilter.openSession(OpenSessionInViewFilter.java:205)
	  at org.springframework.orm.hibernate4.support.OpenSessionInViewFilter.doFilterInternal(OpenSessionInViewFilter.java:140)
	  at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	  at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	  at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:388)
	  at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
	  at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
	  at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
	  at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:440)
	  at org.mortbay.jetty.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:230)
	  at org.mortbay.jetty.handler.HandlerCollection.handle(HandlerCollection.java:114)
	  at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
	  at org.mortbay.jetty.Server.handle(Server.java:326)
	  at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
	  at org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:926)
	  at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:549)
	  at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:212)
	  at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
	  at org.mortbay.io.nio.SelectChannelEndPoint.run(SelectChannelEndPoint.java:410)
	  at org.mortbay.thread.QueuedThreadPool$PoolThread.run(QueuedThreadPool.java:582)
 
input login data and submit:

818546553@qtp-1513757689-1@2865" prio=5 tid=0xf nid=NA runnable
  java.lang.Thread.State: RUNNABLE
	  at org.hibernate.internal.SessionImpl.setFlushMode(SessionImpl.java:1394)
	  at org.springframework.orm.hibernate4.support.OpenSessionInViewFilter.openSession(OpenSessionInViewFilter.java:205)
	  at org.springframework.orm.hibernate4.support.OpenSessionInViewFilter.doFilterInternal(OpenSessionInViewFilter.java:140)
	  at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	  at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	  at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:388)
	  at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
	  at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
	  at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
	  at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:440)
	  at org.mortbay.jetty.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:230)
	  at org.mortbay.jetty.handler.HandlerCollection.handle(HandlerCollection.java:114)
	  at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
	  at org.mortbay.jetty.Server.handle(Server.java:326)
	  at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
	  at org.mortbay.jetty.HttpConnection$RequestHandler.content(HttpConnection.java:943)
	  at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:756)
	  at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:218)
	  at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
	  at org.mortbay.io.nio.SelectChannelEndPoint.run(SelectChannelEndPoint.java:410)
	  at org.mortbay.thread.QueuedThreadPool$PoolThread.run(QueuedThreadPool.java:582)

resume debug and get(F9)

818546553@qtp-1513757689-1@2865" prio=5 tid=0xf nid=NA runnable
  java.lang.Thread.State: RUNNABLE
	  at org.hibernate.internal.SessionImpl.setFlushMode(SessionImpl.java:1394)
	  at org.springframework.orm.hibernate4.HibernateTransactionManager.doBegin(HibernateTransactionManager.java:484)
	  at org.springframework.transaction.support.AbstractPlatformTransactionManager.getTransaction(AbstractPlatformTransactionManager.java:373)
	  at org.springframework.transaction.interceptor.TransactionAspectSupport.createTransactionIfNecessary(TransactionAspectSupport.java:427)
	  at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:276)
	  at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96)
	  at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	  at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92)
	  at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	  at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:653)
	  at com.smart.service.UserService$$EnhancerBySpringCGLIB$$cca1e45d.getUserByUserName(<generated>:-1)
	  at com.smart.web.LoginController.login(LoginController.java:39)
	  at sun.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-1)
	  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	  at java.lang.reflect.Method.invoke(Method.java:498)
	  at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:221)
	  at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:137)
	  at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:110)
	  at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:806)
	  at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:729)
	  at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)
	  at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:959)
	  at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:893)
	  at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
	  at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:872)
	  at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
	  at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
	  at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
	  at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
	  at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1166)
	  at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:77)
	  at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	  at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	  at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:85)
	  at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	  at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	  at com.smart.web.ForumFilter.doFilter(ForumFilter.java:55)
	  at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	  at org.springframework.orm.hibernate4.support.OpenSessionInViewFilter.doFilterInternal(OpenSessionInViewFilter.java:151)
	  at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	  at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	  at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:388)
	  at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
	  at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
	  at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
	  at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:440)
	  at org.mortbay.jetty.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:230)
	  at org.mortbay.jetty.handler.HandlerCollection.handle(HandlerCollection.java:114)
	  at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
	  at org.mortbay.jetty.Server.handle(Server.java:326)
	  at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
	  at org.mortbay.jetty.HttpConnection$RequestHandler.content(HttpConnection.java:943)
	  at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:756)
	  at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:218)
	  at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
	  at org.mortbay.io.nio.SelectChannelEndPoint.run(SelectChannelEndPoint.java:410)
	  at org.mortbay.thread.QueuedThreadPool$PoolThread.run(QueuedThreadPool.java:582)

there is a sentence in TransactionAspectSupport.class 
final TransactionAttribute txAttr = this.getTransactionAttributeSource().getTransactionAttribute(method, targetClass);
txAttr eqauls PROPAGATION_REQUIRED,ISOLATION_DEFAULT

but the ideaSharing do not set AUTO like above

it is below until enableFilters(session);

"1078316340@qtp-494951073-2@6185" prio=5 tid=0x16 nid=NA runnable
  java.lang.Thread.State: RUNNABLE
	  at org.springframework.orm.hibernate4.HibernateTemplate.doExecute(HibernateTemplate.java:338)
	  at org.springframework.orm.hibernate4.HibernateTemplate.executeWithNativeSession(HibernateTemplate.java:309)
	  at org.springframework.orm.hibernate4.HibernateTemplate.find(HibernateTemplate.java:865)
	  at com.ideaSharing.dao.UserDao.getUserByUserName(UserDao.java:27)
	  at com.ideaSharing.service.UserService.getUserByUserName(UserService.java:65)
	  at com.ideaSharing.controller.LoginController.login(LoginController.java:42)
	  at sun.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-1)
	  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	  at java.lang.reflect.Method.invoke(Method.java:498)
	  at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:221)
	  at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:137)
	  at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:110)
	  at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:806)
	  at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:729)
	  at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)
	  at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:959)
	  at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:893)
	  at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
	  at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:872)
	  at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
	  at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
	  at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
	  at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
	  at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1166)
	  at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:77)
	  at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	  at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	  at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:85)
	  at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	  at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	  at com.ideaSharing.controller.ForumFilter.doFilter(ForumFilter.java:55)
	  at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	  at org.springframework.orm.hibernate4.support.OpenSessionInViewFilter.doFilterInternal(OpenSessionInViewFilter.java:151)
	  at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	  at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	  at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:388)
	  at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
	  at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
	  at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
	  at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:440)
	  at org.mortbay.jetty.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:230)
	  at org.mortbay.jetty.handler.HandlerCollection.handle(HandlerCollection.java:114)
	  at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
	  at org.mortbay.jetty.Server.handle(Server.java:326)
	  at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
	  at org.mortbay.jetty.HttpConnection$RequestHandler.content(HttpConnection.java:943)
	  at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:756)
	  at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:218)
	  at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
	  at org.mortbay.io.nio.SelectChannelEndPoint.run(SelectChannelEndPoint.java:410)
	  at org.mortbay.thread.QueuedThreadPool$PoolThread.run(QueuedThreadPool.java:582)

it seems that idea's aop is not working, fk

**Comment by userjia** [comment]
at org.hibernate.internal.SessionImpl.setFlushMode(SessionImpl.java:1394)
	  at org.springframework.orm.hibernate4.HibernateTransactionManager.doBegin(HibernateTransactionManager.java:484)
	  at org.springframework.transaction.support.AbstractPlatformTransactionManager.getTransaction(AbstractPlatformTransactionManager.java:373)
	  at org.springframework.transaction.interceptor.TransactionAspectSupport.createTransactionIfNecessary(TransactionAspectSupport.java:427)
	  at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:276)
	  at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96)
	  at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	  at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92)
	  at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	  at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:653)

idea didn't have this, so that might be aop problem

**Comment by userjia** [comment]
fixed after deleting  the aop definition in idea-dao.xml
